env: "miner"

env_args:
  key: null
  time_limit: 100

test_greedy: True
test_nepisode: 200
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 1050000
